import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Paper, Stack, Group, Text, Anchor, Divider } from '@mantine/core';
const VISIT_OPTIONS = {
    'within-6-months': 'Within 6 months',
    '6-12-months': '6-12 months',
    'over-a-year': 'Over a year',
    'never': 'Never',
};
export const BookingSummary = ({ locationName, locationAddress, date, time, patientInfo, onEdit, }) => {
    return (_jsxs(Stack, { gap: "lg", children: [_jsxs(Paper, { p: "lg", radius: "md", withBorder: true, children: [_jsxs(Group, { justify: "space-between", mb: "md", children: [_jsx(Text, { fw: 600, size: "lg", children: "Location" }), _jsx(Anchor, { onClick: () => onEdit(1), size: "sm", children: "Edit" })] }), _jsxs(Stack, { gap: "xs", children: [_jsx(Text, { children: locationName }), _jsx(Text, { size: "sm", c: "dimmed", children: locationAddress })] })] }), _jsxs(Paper, { p: "lg", radius: "md", withBorder: true, children: [_jsxs(Group, { justify: "space-between", mb: "md", children: [_jsx(Text, { fw: 600, size: "lg", children: "Date & Time" }), _jsx(Anchor, { onClick: () => onEdit(2), size: "sm", children: "Edit" })] }), _jsxs(Stack, { gap: "xs", children: [_jsxs(Text, { children: [_jsx("strong", { children: "Date:" }), " ", date] }), _jsxs(Text, { children: [_jsx("strong", { children: "Time:" }), " ", time] })] })] }), _jsxs(Paper, { p: "lg", radius: "md", withBorder: true, children: [_jsxs(Group, { justify: "space-between", mb: "md", children: [_jsx(Text, { fw: 600, size: "lg", children: "Patient Information" }), _jsx(Anchor, { onClick: () => onEdit(3), size: "sm", children: "Edit" })] }), _jsxs(Stack, { gap: "xs", children: [_jsxs(Group, { children: [_jsx(Text, { fw: 500, w: "50%", children: "Date of Birth:" }), _jsx(Text, { children: patientInfo.dateOfBirth })] }), _jsx(Divider, {}), _jsxs(Group, { children: [_jsx(Text, { fw: 500, w: "50%", children: "Dental Insurance:" }), _jsx(Text, { children: patientInfo.hasInsurance === 'yes' ? 'Yes' : 'No' })] }), _jsx(Divider, {}), _jsxs(Group, { children: [_jsx(Text, { fw: 500, w: "50%", children: "Last Dental Visit:" }), _jsx(Text, { children: VISIT_OPTIONS[patientInfo.lastDentalVisit] })] }), _jsx(Divider, {}), _jsxs(Group, { children: [_jsx(Text, { fw: 500, w: "50%", children: "Dental Pain:" }), _jsx(Text, { children: patientInfo.hasDentalPain === 'yes' ? 'Yes' : 'No' })] }), patientInfo.allergies && (_jsxs(_Fragment, { children: [_jsx(Divider, {}), _jsxs(Group, { children: [_jsx(Text, { fw: 500, w: "50%", children: "Allergies:" }), _jsx(Text, { children: patientInfo.allergies })] })] })), patientInfo.additionalNotes && (_jsxs(_Fragment, { children: [_jsx(Divider, {}), _jsxs(Group, { children: [_jsx(Text, { fw: 500, w: "50%", children: "Additional Notes:" }), _jsx(Text, { children: patientInfo.additionalNotes })] })] }))] })] })] }));
};
